development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] %>
  base_path: '/development'
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] %>
  base_path: '/test'
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] %>
  base_path: '/prod'
