# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_DEV_URL'] || "http://127.0.0.1:8983/solr/scholarspace_dev" %>
test: &test
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8983/solr/scholarspace_test" %>
production:
  url: <%= ENV['SOLR_PROD_URL'] || "http://127.0.0.1:8983/solr/scholarspace_prod" %>
